spring:
 application:
  name: spring-rest-api-demo1
 database:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
 h2:
  console:
   enabled: true
   path: /h2-console
logging:
  level:
   org:
    springframework:
     web: DEBUG
     validation: DEBUG 

 